### ISSUE TITLE
Node version and CircleCI

### ISSUE THREAD

**Issue by cunning-folk** [gblakeman/yassss#6]
@gblakeman I got this from CircleCI this morning

```
#!/bin/bash -eo pipefail
yarn lint:js
yarn lint:css
yarn run v1.21.1
error yassss@0.0.1: The engine "node" is incompatible with this module. Expected version "12.14.0". Got "12.14.1"
error Commands cannot run with an incompatible environment.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exited with code exit status 1
CircleCI received exit code 1
```

Do I need to upgrade my local version of node?

Is there a way I can subscribe to CircleCI's chages so I can keep up?

Any help appreciated!

**Comment by gblakeman** [comment]
@cunning-folk I’ll look into this later today. I thought I had the Node version locked-in on CircleCI, but maybe it’s floating. It shouldn’t need to be updated this often…
